# Generated by Django 5.1.4 on 2024-12-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyrate',
            old_name='date_updated',
            new_name='date',
        ),
    ]
